version: '3'

services:
  eureka-server:
    hostname: eureka-server
    image: ahmd66699/aqarati-service-discovery:1.0.0
    ports:
      - "8761:8761"
    networks:
      - aqarati-network
  gateway:
    hostname: gateway
    image: ahmd66699/aqarati-gateway:1.0.1
    ports:
      - "8888:8888"
    networks:
      - aqarati-network
  nginx-reverse-proxy:
    image: ahmd66699/aqarati-nginx-reverse-proxy:0.1V-Docker
    ports:
      - "80:80"
    networks:
      - aqarati-network

  auth-service:
    image: ahmd66699/aqarati-auth-service:1.0.0
    ports:
      - "0:8443"
    networks:
      - aqarati-network
  user-service:
    image: ahmd66699/aqarati-user-service:1.0.1
    ports:
      - "0:8444"
    networks:
      - aqarati-network
  property-service:
    image: ahmd66699/aqarati-property-service:1.0.2-SNAPSHOT
    ports:
      - "0:8666"
    networks:
      - aqarati-network
    depends_on:
      - redis
  document-service:
    image: ahmd66699/aqarati-document-service:1.0.0
    ports:
      - "0:8665"
    networks:
      - aqarati-network
  image-service:
    image: ahmd66699/aqarati-image-service:1.0.0
    ports:
      - "0:7654"
    networks:
      - aqarati-network
  chat-service:
    image: ahmd66699/aqarati-chat-service:1.0.0
    ports:
      - "8080:8080"
    networks:
      - aqarati-network
  redis:
    image: redis:7.2.4-alpine
    ports:
      - "6379:6379"
    networks:
      - aqarati-network
networks:
  aqarati-network:
    driver: bridge
